Added first two planet orbits to (Im)plot.
The class Ellipse would not work due to error C4430 (forward compilation error), so I made an identical one called EllipseFunction which does.